version: "3.9"

services:
  node:
    image: node:20
    container_name: node_app
    working_dir: /usr/src/app
    volumes:
      - ./src:/usr/src/app
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - internal

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./bdd:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal
    # No ports exposed -> only Node.js can access it

networks:
  internal:
    driver: bridge
